### ISSUE TITLE
Error with Google Login

### ISSUE THREAD

**Issue by insideth** [arckinteractive/elgg_hybridauth#15]
error:default
User profile request failed! Google returned an error: exception 'Exception' with message 'The Authorization Service has return: invalid_client' in /home/www/redup_triploader_com/htdocs/mod/elgg_hybridauth/vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php:84 Stack trace: #0 /home/www/redup_triploader_com/htdocs/mod/elgg_hybridauth/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Provider_Model_OAuth2.php(118): OAuth2Client->authenticate('4/A13EvyOz5lvwl...') #1 /home/www/redup_triploader_com/htdocs/mod/elgg_hybridauth/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php(182): Hybrid_Provider_Model_OAuth2->loginFinish() #2 /home/www/redup_triploader_com/htdocs/mod/elgg_hybridauth/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php(55): Hybrid_Endpoint->processAuthDone() #3 /home/www/redup_triploader_com/htdocs/mod/elgg_hybridauth/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php(71): Hybrid_Endpoint->__construct(NULL) #4 /home/www/redup_triploader_com/htdocs/mod/elgg_hybridauth/views/default/resources/hybridauth/endpoint.php(8): Hybrid_Endpoint::process() #5 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/ViewsService.php(364): include('/home/www/redup...') #6 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/ViewsService.php(299): Elgg\ViewsService->renderViewFile('resources/hybri...', Array, 'default', true) #7 /home/www/redup_triploader_com/htdocs/engine/lib/views.php(355): Elgg\ViewsService->renderView('resources/hybri...', Array, false, '') #8 /home/www/redup_triploader_com/htdocs/mod/elgg_hybridauth/start.php(87): elgg_view('resources/hybri...') #9 [internal function]: elgg_hybridauth_page_handler(Array, 'hybridauth') #10 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Router.php(80): call_user_func('elgg_hybridauth...', Array, 'hybridauth') #11 /home/www/redup_triploader_com/htdocs/index.php(60): Elgg\Router->route(Object(Elgg\Http\Request)) #12 {main}

**Comment by beck24** [comment]
No longer relevant
