### ISSUE TITLE
Profile image not correctly imported at least from Facebook

### ISSUE THREAD

**Issue by michelesbw** [arckinteractive/elgg_hybridauth#21]
Hello,
Elgg 2.3 over https and HybridAuth 1.4.1.
When signing up via Facebook, user avatar (profile image) seems not to be correctly imported, it is showed as broken, see screenshot below. Cheers 
![screenshot-socialbusinessworld org 2017-01-05 18-30-30](https://cloud.githubusercontent.com/assets/5203511/21690561/1ea5c752-d375-11e6-99e5-855341d386e9.png)

**Comment by hypeJunction** [comment]
Which Elgg version?

**Comment by michelesbw** [comment]
2.3 as above mentioned ;)

**Comment by hypeJunction** [comment]
Sorry :) need to investigate

**Comment by michelesbw** [comment]
I can confirm it's from Facebook and also email address is being imported not only in user's default email field but also into another email field I added via profile manager which should be only filled in voluntarily by users because showed publicly.

**Comment by hypeJunction** [comment]
Fixed in https://github.com/arckinteractive/elgg_hybridauth/commit/8d2733d9f97e9d1308e63823dddb17faa4201b96
