### ISSUE TITLE
Profile manager's email field populated but shouldn't be so (?)

### ISSUE THREAD

**Issue by michelesbw** [arckinteractive/elgg_hybridauth#22]
Hello,
on our site we have created through Profile Manager plugin a "contactemail" field users can choose to fill in and publicly show it but when using hybridauth both this and Elgg's default email address needed to signup are being populated.
I think this is a mistake, the first shouldn't while of course the second should.
Cheers

**Comment by hypeJunction** [comment]
`contactemail` is the default Elgg profile field and it's populated with the data we receive from provider. I think this is a site specific issue that I personally don't want to deal with. So, unless someone else wants to fix it...

**Comment by michelesbw** [comment]
Hmm of course I'm not sure but isn't Elgg's default: <input name="email" class="elgg-input-text" id="register-email" type="text"> ?
contactemail field was added by me via profile manager, I'm pretty sure about it

**Comment by hypeJunction** [comment]
contactemail is the default profile field. https://github.com/Elgg/Elgg/blob/master/engine/lib/users.php#L628

**Comment by michelesbw** [comment]
Could it be that in previous versions that field name was simply email? I created that field years ago via Profile Manager. In fact, users can leave "my" contactemail field empty while the "email" field gets populated when registering normally via /register page...

**Comment by beck24** [comment]
IK is right that it's the elgg default profile field, and you've just recreated it in profile manager.  In elgg (and profile_manager) it's an optional field and defaults to public-facing.  I'm not sure why it should be populated through this though, I wouldn't want my facebook login email exposed on a third party site because of single-sign-on.

**Comment by hypeJunction** [comment]
@beck24 Following that logic we should just stop populating any of the fields.

**Comment by beck24** [comment]
It's been a while since I've used it, I don't remember what it populates offhand.  Name and profile pic for sure, and those are fine/expected.  I think email is probably a special case, most social networks don't expose it to others, or in the case of facebook it's a specific opt-in process to make it public.  We need the email by necessity to create the account, but I would argue we shouldn't publish it automatically.  Perhaps we make it configurable behaviour?  Then the site owner can decide how it should work.

**Comment by michelesbw** [comment]
You're surely right guys but there's something strange I don't understand.
Users who create accounts via /register page only need to fill in the "email" field. In the case "contactemail" ad "email" were the same fields, once signed up both fields should be filled in, right? But this is not true, this only happens through HybridAuth (Facebook).
What am I missing?

**Comment by beck24** [comment]
No, elgg is doing it correctly.  It's using the signup email for the 'login' email, which isn't exposed to others, it's a property of the user.  The contactemail is a metadata profile field that is exposed to other users, that is populated in elgg by filling out the profile information and entering that field.
With hybridauth it takes the email address it receives from the provider and assigns it to both the email property as well as the contactemail metadata.

**Comment by michelesbw** [comment]
Thanks for explanation! So, basically what I would expect when using this plugin (or others) for registration is filling in only mandatory fields and metadata by Elgg and optionally (admin's settings) others but maybe this my bad expectation :)

**Comment by hypeJunction** [comment]
Valid expectation, which might materialise some time in future :) I wish holy spirit could make pull requests

**Comment by michelesbw** [comment]
I wish I could make or fund all pull requests for valid expectations...holy spirit won't help me on this unfortunately :D
You know, never take my comments as criticisms but possibly bug reports or UX. In this case I really think nobody (site admins or users) like to expose this info so...not site specific, possible improvement of this plugin when funds and time will allow it :)

**Comment by hypeJunction** [comment]
It's going to take 5 minutes to implement. Just being difficult :)

**Comment by michelesbw** [comment]
Well...then I can fund it! :D
