### ISSUE TITLE
Broken URLs in non-latin profile names

### ISSUE THREAD

**Issue by RiverVanRain** [arckinteractive/elgg_hybridauth#24]
After updating to Elgg 2.3.1 all URLs/icons of the profiles with non-latin names (e.g. authorisation via Google) are broken:

> **Before**: http://link-to-site/profile/ИмяПользователя
> **After**: http://link-to-site/http://link-to-site/profile/ИмяПользователя

This issue is related with updated [output lib](https://github.com/Elgg/Elgg/pull/10694/commits/48a51709c956b5a676711a3febb32c65a5df1e0e) (_I've checked it with 2.3 (all works like a charm)_) in Elgg 2.3.1

**Comment by RiverVanRain** [comment]
All works after this [merge](https://github.com/Elgg/Elgg/pull/10772)

**Comment by beck24** [comment]
Closing this as it appears to be an issue with core
