### ISSUE TITLE
Registration doesn't check whether email is already being used?

### ISSUE THREAD

**Issue by juho-jaakkola** [arckinteractive/elgg_hybridauth#25]
Apparently email address is not checked from existing accounts before creating a new one.

I'm using the Facebook authentication, and I keep finding duplicate accounts. One created with the registration form and one with Facebook authentication.

Often users do not remember whether they originally registered manually or via facebook, so they try both which results in two separate accounts. The hybridauth plugin should take this into consideration and prevent duplicate accounts.

**Comment by beck24** [comment]
I'm 100% positive it already does this, I was working with it in a project as recently as a couple of days ago where this was tested.  Are you sure they're identical email addresses?

**Comment by juho-jaakkola** [comment]
Ok, good to hear that this has been tested recently. I will do some debugging to rule out any other hooks/features that might accidentally bypass the email check.
