### ISSUE TITLE
Facebook is broken or so it seems. Also needs to be updated

### ISSUE THREAD

**Issue by ernestbuffington** [arckinteractive/elgg_hybridauth#32]
New facebook Web Applications now default to v2.10 API and in this plugin, it is using v2.8

On another note same API call, facebook keeps saying that the domain is not set up in the application. This I assume is because the facebook programmers do not keep up with new TLDs. 

.network is perfectly valid but when the API makes the call it keeps saying that it Can't load URL.
![image1](https://user-images.githubusercontent.com/17893144/31928169-19df0262-b865-11e7-91cd-e0be808df2b2.png)

**Comment by Jarvil** [comment]
Hello,

I have run in to this same issue, is this fixed? @beck24

**Comment by beck24** [comment]
Sorry, didn't see this.  That's not an issue with this plugin, you're missing data on your FB app settings
