### ISSUE TITLE
Facebook 2.12 API support?

### ISSUE THREAD

**Issue by Jarvil** [arckinteractive/elgg_hybridauth#37]
Hello,

When I now create a new facebook app it only gives me option to use API 2.12, does this plugin even support API 2.12? Will it? @beck24

**Comment by Jarvil** [comment]
Hello @beck24

**Comment by hypeJunction** [comment]
This plugin is a wrapper around hybridauth and doesn't support anything on its own. Make sure you have the latest version of hybridauth by running composer update.
